#!/data/data/com.termux/files/usr/bin/bash

clear && echo -e '\033[44;97m  OhMyObsidian  \033[0m'

source /storage/emulated/0/Documents/Repository/OhMyObsidian/bashrc

# Turn off untrusted repo protection
cd "$SCRIPTS_REPO_PATH"
existing_dirs=$(git config --global --get-all safe.directory)

if [[ ! $existing_dirs == *"*"* ]]; then
    git config --global --add safe.directory "*" > /dev/null 2>&1
fi

# Update scripts repo
cd "$SCRIPTS_REPO_PATH"
git fetch > /dev/null 2>&1
git_status=$(git status)

if [[ "$git_status" == *"Your branch is behind"* ]]; then
  if [[ "$git_status" == *"Changes not staged for commit"* || "$git_status" == *"Changes to be committed"* ]]; then
    echo -e "${RED}Il y a des modifications locales dans le dépôt de scripts qui bloqueraient un git pull. Sachez simplement que vous manquez des mises à jour. Continuer le script...${RESET}"
  else
    if git pull -q > /dev/null 2>&1; then
      echo -e "${GREEN}Le dépôt de scripts a été mis à jour !${RESET}"
    else
      echo -e "${RED}Échec de la mise à jour du dépôt de scripts.${RESET}"
      exit 1
    fi

    # Check if 'setup' file in repo is different from the one in $HOME/OhMyObsidian
    if ! diff "${SCRIPTS_REPO_PATH}/setup" "$HOME/OhMyObsidian/setup" > /dev/null; then
        cmd="cp \"${SCRIPTS_REPO_PATH}/setup\" \"${HOME}/OhMyObsidian/\""
        echo -e "$cmd" | termux-clipboard-set
        echo -e "${RED}Le fichier 'setup' a été mis à jour.\nExécutez la commande suivante pour le mettre à jour (elle est déjà dans votre presse-papiers) :\n${YELLOW}${cmd}${RESET}"
        echo -e "${RED}Sortie du script.${RESET}"
        exit 1
    fi
  fi
fi

# Make sure Termux has file permissions
if touch "$STORAGE_PATH"/.termux_permission_check > /dev/null 2>&1; then
  rm "$STORAGE_PATH"/.termux_permission_check > /dev/null 2>&1
else
  echo -e "${RED}Termux n'a pas les permissions de fichier.${RESET}"
  echo -e "${BLUE}Exécutez 'termux-setup-storage' ou donnez la permission depuis le menu des permissions de Termux sur Android.${RESET}"
fi

# Enable allow-external-apps
if grep -q '^# allow-external-apps = true' $HOME/.termux/termux.properties; then
  sed -i 's/^# allow-external-apps = true/allow-external-apps = true/' $HOME/.termux/termux.properties > /dev/null 2>&1
  termux-reload-settings > /dev/null 2>&1
fi

# Create SSH keys
if [ ! -f ~/.ssh/id_rsa ]; then
  echo -e "${BLUE}Création d'une clé SSH...${RESET}"
  ssh-keygen -t rsa -N "" -f ~/.ssh/id_rsa > /dev/null 2>&1

  if cat ~/.ssh/id_rsa.pub | termux-clipboard-set; then
    echo -e "${BLUE}La clé publique SSH a été copiée dans votre presse-papiers.${RESET}"
    echo -e "${BLUE}Veuillez la coller dans les paramètres d'authentification des clés SSH de votre hôte Git.${RESET}"
  else
    echo -e "$YELLOW"
    cat ~/.ssh/id_rsa.pub
    echo -e "\n$RESET"
    echo -e "${BLUE}Copiez la clé ci-dessus (en ${YELLOW}jaune${BLUE}) et collez-la dans les paramètres d'authentification des clés SSH de votre hôte Git.${RESET}"
  fi
else
  echo -e "$YELLOW"
  cat ~/.ssh/id_rsa.pub
  echo -e "\n${BLUE}Voici votre clé SSH (ci-dessus en ${YELLOW}jaune${BLUE}) au cas où vous voudriez la copier.${RESET}"
fi

# Copy and chmod scripts to $HOME/OhMyObsidian
DEST_DIR="$HOME/OhMyObsidian"

for file in "$SCRIPTS_REPO_PATH"/*; do
  filename=$(basename -- "$file")
  cp "$file" "$DEST_DIR/" > /dev/null 2>&1
  chmod +x "$DEST_DIR/$filename" > /dev/null 2>&1
done

# Define configuration files

BASHRC_FILE="/data/data/com.termux/files/usr/etc/bash.bashrc"
ZSHRC_FILE="$HOME/.zshrc"

declare -a LINES_TO_ADD=(
  "source $SCRIPTS_REPO_PATH/bashrc # obsidian-sync-source-tag"
)

modify_or_add_line_with_tag() {
  local line=$1
  local file=$2
  local tag=$(echo "$line" | awk -F'#' '{print $2}')

  sed -i "/$tag/d" "$file" > /dev/null 2>&1
  echo "$line" >> "$file"
}

# Add to bash.bashrc
for line in "${LINES_TO_ADD[@]}"; do
  modify_or_add_line_with_tag "$line" "$BASHRC_FILE"
done

# If zsh is installed, add to .zshrc 
if command -v zsh > /dev/null 2>&1; then
  for line in "${LINES_TO_ADD[@]}"; do
    modify_or_add_line_with_tag "$line" "$ZSHRC_FILE"
  done
fi

# Make sure user.name and user.email is populated
git_name=$(git config --global user.name)
git_email=$(git config --global user.email)

if [ -z "$git_name" ]; then
  read -p "Entrez votre git user.name : " git_name
  git config --global user.name "$git_name" > /dev/null 2>&1
fi

if [ -z "$git_email" ]; then
  read -p "Entrez votre git user.email : " git_email
  git config --global user.email "$git_email" > /dev/null 2>&1
fi

# Git config
git config --global core.editor nano > /dev/null 2>&1
git config --global merge.conflictstyle diff3 > /dev/null 2>&1

# Create and access the Obsidian directory
touch $NOTIFICATION_PATH > /dev/null 2>&1

mkdir -p $OBSIDIAN_DIR_PATH > /dev/null 2>&1
cd $OBSIDIAN_DIR_PATH

echo -e "\n${GREEN}Configuration terminée${RESET}\n"